---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/cymetrix/public_html/blog/
    - echo "Starting deployment to $DEPLOYPATH"
    - rm -rf $DEPLOYPATH/*
    - /bin/cp -r . $DEPLOYPATH
    - echo "Deployment completed successfully!"
